version: '3.4'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       
   wordpress:
     depends_on:
       - db
     build: .
     ports:
      - "5000:80"
     environment:
       DB_ENV_HOST: db:3306
       DB_ENV_USER: wordpress
       DB_ENV_PASSWORD: wordpress
       DB_ENV_NAME: wordpress
volumes:
    db_data: {}